services:
  # 1. Base de données MySQL
  db:
    image: mysql:8.2
    container_name: suivie-db
    restart: always
    environment:
      MYSQL_DATABASE: suivie_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - suivie_db_data:/var/lib/mysql

  # 2. Backend Laravel
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: suivie-api
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=suivie_db
      - DB_USERNAME=root
      - DB_PASSWORD=root

  # --- AJOUT DE LA STACK MONITORING ---

  # 3. Elasticsearch (Le cerveau qui stocke les logs)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: suivie-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  # 4. Logstash (Le facteur qui envoie les emails)
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: suivie-logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5044:5044"
      - "5000:5000/udp"
    depends_on:
      - elasticsearch

  # 5. Kibana (L'interface pour voir les logs)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: suivie-kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  suivie_db_data: