sonar.projectKey=lustrellesobze_Integration_projet
sonar.organization=lustrellesobze
sonar.projectName=Integration Projet CI/CD
sonar.projectVersion=1.0
sonar.sources=app,routes,database
sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/**
sonar.php.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8