global:
  scrape_interval: 15s        # Collecte toutes les 15 secondes
  evaluation_interval: 15s

scrape_configs:

  # ── Prometheus lui-même ───────────────────
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ── Métriques système (CPU, RAM, réseau) ──
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # ── Métriques Laravel ─────────────────────
  - job_name: 'laravel'
    static_configs:
      - targets: ['app:8001']
    metrics_path: '/metrics'   # on ajoutera cette route dans Laravel