apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: default
spec:
  selector:
    app: laravel
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
      nodePort: 30080